### ISSUE TITLE
toDouble was Called on null

### ISSUE THREAD

**Issue by nitishpatel** [apgapg/pie_chart#10]
`I/flutter (30917): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (30917): The following NoSuchMethodError was thrown building PieChart(dirty, state:
I/flutter (30917): _PieChartState#f7d87(ticker active)):
I/flutter (30917): The method 'toDouble' was called on null.
I/flutter (30917): Receiver: null
I/flutter (30917): Tried calling: toDouble()
I/flutter (30917):
I/flutter (30917): When the exception was thrown, this was the stack:
I/flutter (30917): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
I/flutter (30917): #1      double.+ (dart:core-patch/double.dart:17:23)
I/flutter (30917): #2      new PieChartPainter (package:pie_chart/pie_chart.dart:214:21)
I/flutter (30917): #3      _PieChartState.build (package:pie_chart/pie_chart.dart:112:28)
I/flutter (30917): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
I/flutter (30917): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
I/flutter (30917): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (30917): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (30917): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (30917): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (30917): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (30917): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (30917): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (30917): #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (30917): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (30917): #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (30917): #31     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4063:11)
I/flutter (30917): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #33     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4982:32)
I/flutter (30917): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (30917): #39     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (30917): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (30917): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #45     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (30917): #46     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (30917): #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #51     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (30917): #52     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (30917): #53     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (30917): #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #56     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (30917): #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #61     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (30917): #62     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (30917): #63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #65     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (30917): #66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #70     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (30917): #71     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (30917): #72     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (30917): #73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #76     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #77     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (30917): #78     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (30917): #79     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (30917): #80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #83     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (30917): #85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (30917): #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #90     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (30917): #91     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (30917): #92     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #96     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (30917): #97     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (30917): #98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (30917): #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #102    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #103    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (30917): #104    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (30917): #105    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (30917): #106    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #108    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (30917): #109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #113    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (30917): #114    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (30917): #115    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #117    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (30917): #118    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #120    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (30917): #121    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #123    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (30917): #124    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #125    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #126    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (30917): #127    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #128    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #130    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #131    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (30917): #132    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (30917): #133    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (30917): #134    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #135    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #136    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #137    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #138    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (30917): #139    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (30917): #140    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): 2
I/flutter (30917): 3
I/flutter (30917): 2.0
I/flutter (30917): 3.0
I/flutter (30917): #143    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #144    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (30917): #145    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (30917): #146    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (30917): #147    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #148    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #149    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (30917): #150    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #151    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #153    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #154    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (30917): #155    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (30917): #156    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #157    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #158    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (30917): #159    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #160    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #162    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #163    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (30917): #164    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (30917): #165    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (30917): #166    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #167    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #168    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #169    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #170    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (30917): #171    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (30917): #172    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #173    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #174    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (30917): #175    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #176    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #178    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #179    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (30917): #180    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (30917): #181    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #182    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #183    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #184    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #185    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (30917): #186    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (30917): #187    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (30917): #188    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #189    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #190    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #191    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #192    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (30917): #193    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (30917): #194    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (30917): #195    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (30917): #196    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (30917): #197    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4659:32)
I/flutter (30917): #198    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter (30917): #199    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (30917): #200    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:607:16)
I/flutter (30917): #201    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (30917): #202    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #203    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #204    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (30917): #205    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (30917): #206    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #207    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #208    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (30917): #209    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (30917): #210    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (30917): #211    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (30917): #212    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #213    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #214    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (30917): #215    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (30917): #216    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (30917): #217    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (30917): #218    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (30917): #219    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (30917): #220    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (30917): #221    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (30917): #222    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
I/flutter (30917): #223    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (30917): #224    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter (30917): #225    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter (30917): #226    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter (30917): #227    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter (30917): #231    _invoke (dart:ui/hooks.dart:219:10)
I/flutter (30917): #232    _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter (30917): (elided 3 frames from package dart:async)
I/flutter (30917): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (30917): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/chatty  (30917): uid=10656(com.example.mydb_todo) 1.ui identical 4 lines
I/flutter (30917): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on `null.``

**Comment by apgapg** [comment]
I guess the data entry in null. Thats why converting a value to double is throwing error. Can you once recheck that your data isnt null anywhere?

**Comment by nitishpatel** [comment]
No  I cleary add the data as per the example

**Comment by apgapg** [comment]
Okay thanks for raising this issue. Will check and revert soon

**Comment by apgapg** [comment]
@nitishpatel I ran the example and its working correctly. I certainly believe there's some issue with data. Could you please share some sample code/data to help me replicate?
