### ISSUE TITLE
Center widget is needed

### ISSUE THREAD

**Issue by bilalsammour** [apgapg/pie_chart#101]
It is good to have the `centerText` property, but it is way better to have a new property of `centerWidget` to be anything we want inside the chart.

Note: It is doable to use the `Wrap` widget to add a widget at the center of the `PieChart` widget but the problem is it will not be at the center of the chart due to the legend size.

**Comment by apgapg** [comment]
Good point.
Will try adding the `centerWidget` too.

**Comment by apgapg** [comment]
Hi @bilalsammour i have added center widget. 
Please see if this fulfills your requirement.
Added a screenshot and implementation code in README.

**Comment by bilalsammour** [comment]
Thank you @apgapg .
Note: It is still not available on pub.dev, and also, `centerWidget` is not mentioned in the Full Implementation section.

**Comment by apgapg** [comment]
@bilalsammour i havent published it yet.
Just added the feature on master branch.

Did the new section of Center widget in readme helped?

**Comment by bilalsammour** [comment]
@apgapg yes so useful, thank you.

**Comment by apgapg** [comment]
Let me then release it to pub dev now

**Comment by apgapg** [comment]
v5.4.0 is available on pub.dev
