### ISSUE TITLE
Enable selecting piechart slice starting angle

### ISSUE THREAD

**Issue by chwiz143** [apgapg/pie_chart#13]
First thank you for your work. This is the easiest to use flutter chart plugin on pub!

Currently the piechart starts animating from the right side of the circle (from 3 o'clock).
Is it possible to set a starting angle from where the first slice will draw?

Like in the example image below, change "starting angle" from 90° -> 0°

![change_starting_angle_for_piechart](https://user-images.githubusercontent.com/48340339/64599155-dd9bce00-d3f3-11e9-9c48-f257de53c9aa.jpg)

**Comment by apgapg** [comment]
Thanks for those kind and motivating words. Yes there is a parameter 'initialAngle: math.pi*0.5' with which you can change the start angle.
