### ISSUE TITLE
[Feature Request] Column View

### ISSUE THREAD

**Issue by MilesAdamson** [apgapg/pie_chart#18]
Hi, absolutely loving this plugin for my workout app. Got the visual breakdown of what they train in like 5 minutes.

A nice feature might be a column view, where the pie chart is on top and the legend is below. This would allow each to be larger so I could use bigger fonts inside the pie chat.

**Comment by apgapg** [comment]
Thanks for compliment. Glad to know it proved useful to you.
Your Request is implemented in v3.0.0 . Go checkitout soon. See README for details.
***NOTE: This is a little breaking change, so do care after upgrading
