### ISSUE TITLE
Can legend position be costomized?

### ISSUE THREAD

**Issue by cuitao1988** [apgapg/pie_chart#2]
Can legend position be costomized?
Such as under the chart

**Comment by apgapg** [comment]
Not currently. But thanks for the idea. Will incorporate the same in next release

**Comment by apgapg** [comment]
I think i should provide a legend visibility bool also.

**Comment by monxarat** [comment]
I have the same issue.

Could you support show options between percent and value?

**Comment by apgapg** [comment]
Its already there. I have given a parameter bool for that.

**Comment by apgapg** [comment]
@cuitao1988 Added a bool 'showLegends' to toggle visibility of Legends. Shifting the position to downward is little complicated. I will be happy to accept any PR. Thanks

**Comment by phelipepalte** [comment]
Any result from shifting the position to bottom?

**Comment by apgapg** [comment]
Will implement in next version. Thanks @phelipepalte  for pointing out

**Comment by xsahil03x** [comment]
@apgapg please merge the previous PR so that I can create another one for this feature.

**Comment by xsahil03x** [comment]
@apgapg This can be closed now as fixed in #17

**Comment by apgapg** [comment]
Already on master branch. Closing
