### ISSUE TITLE
showLegends = false causes exception

### ISSUE THREAD

**Issue by PramodJoshi** [apgapg/pie_chart#22]
Hi, is it possible to hide legends? I am displaying pie chart inside a row widget and I tried showLegends = false but i am getting '**Row's children must not contain any null value, but a null value was found at index 1**' exception. Any idea?

**Comment by apgapg** [comment]
Hi @PramodJoshi Issue has been fixed in v3.1.1
Thanks for opening issue

**Comment by PramodJoshi** [comment]
Nice. Keep up the great work. Thanks!
