### ISSUE TITLE
A few issues since upgrading from 2.0.0

### ISSUE THREAD

**Issue by guyzk** [apgapg/pie_chart#23]
Hi!

A few issues since upgrading from 2.0.0
1) showChartValuesOutside: The are not totally outside, they are partially on the chart which in my opinion doesn't look as good
2) Legend position that was added looks bad on RTL languages.
a) It is not aligned to the start of the container
b) There is not enough padding between the chart and the legends
I believe that it will be better to have LegendPosition.start and LegendPosition.end instead of left and right.
Please test on a device with and RTL language.

Thanks for this great package. Hope you could get to fixing these issues soon.

**Comment by apgapg** [comment]
Thanks for such descriptive info. Will definetly look into it and revert

**Comment by guyzk** [comment]
> Thanks for such descriptive info. Will definetly look into it and revert

Hi, 
I there any estimation for a fix? My app has several languages 2 of which are RTL and this is critical for me.
Thanks!

**Comment by apgapg** [comment]
Sorry it just slipped from my mind. Will fix up tomorrow for sure

**Comment by guyzk** [comment]
Any updates?

**Comment by apgapg** [comment]
All of these are fixed on master branch. Check them LIVE https://apgapg.github.io/pie_chart/
