### ISSUE TITLE
How to place labels completely outside of the ring? 

### ISSUE THREAD

**Issue by blbhargav** [apgapg/pie_chart#28]
Hi Bro, Is there a way we can place labels completely outside the ring like the below?

![download (1)](https://user-images.githubusercontent.com/24856031/74508402-fec59500-4f24-11ea-99b4-d5a98829958d.png)

**Comment by apgapg** [comment]
Not right now. I havent given any factor for that.
You can fork the repo and change that factor in the code. Its just changing of a digit

**Comment by apgapg** [comment]
Its fixed. Check Live https://apgapg.github.io/pie_chart/
