### ISSUE TITLE
Change label position 

### ISSUE THREAD

**Issue by tony123S** [apgapg/pie_chart#29]
The label now is displayed vertically.  It is possible to displayed  horizontally? 

I want change the legend position to top, and displayed the label horizontally.

Thanks.

**Comment by apgapg** [comment]
You can switch off labels  and can define your own widgets for  legends

**Comment by tony123S** [comment]
Is 3.1.1 is the latest? I paste pie_chart.dart to my project but get

> 
> Compiler message:
> ../../flutter_linux_v1.5.4-hotfix.2-stable.tar%20(1)/flutter/.pub-cache/hosted/pub.dartlang.org/pie_chart-3.1.1/lib/src/pie_chart.dart:152:15: Error: No named parameter with the name 'formatChartValues'.
>               formatChartValues: widget.formatChartValues
>               ^^^^^^^^^^^^^^^^^

**Comment by apgapg** [comment]
Yes moving from 2.x.x to 3.x.x breaking changes in syntax were introduced. You have to make some minor changes if you want . to upgrade

**Comment by tony123S** [comment]
Thanks for your reply.

I have  modified `pie_chart.dart` and now I want to roll it back to the previous version. So I paste `pie_chart.dart` from github again, but get the error message. 

I have checked the version in pub.yaml, it is `3.1.1`.

**Comment by apgapg** [comment]
no just add pie_chart: 2.0.0 . The error will go away

**Comment by apgapg** [comment]
May be the code on master branch got break, just use above version

**Comment by tony123S** [comment]
But if I downgrade the version, I can't use               `chartValueBackgroundColor`    ,`legendPosition`                        `chartType`....

**Comment by apgapg** [comment]
can you share a quick gist of code? Let me fix it quickly

**Comment by apgapg** [comment]
https://pub.dev/packages/pie_chart#-changelog-tab-
Try changing versions.
Sorry for inconvinice will fix it up asap and provide release

**Comment by tony123S** [comment]
You know what are the issues? Still need me to share the code?

**Comment by apgapg** [comment]
Okay let me test it on my own and get back to you

**Comment by tony123S** [comment]
Thanks

**Comment by apgapg** [comment]
You were copy pasting stuffs thats why you might have missed the function.
Paste both pie_chart and chart painter dart class

**Comment by apgapg** [comment]
v3.1.1 is working fine. No issues

**Comment by tony123S** [comment]
Sorry for that. I'm so careless..

**Comment by apgapg** [comment]
Glad issue is resolved. Please close it if it works fine.
Thanks

**Comment by tony123S** [comment]
Ok,thanks

**Comment by tony123S** [comment]
2
