### ISSUE TITLE
Data changed but PieChart was not changed.

### ISSUE THREAD

**Issue by leehuwuj** [apgapg/pie_chart#3]
I used FutureBuilder to mock data from sqflite then build a PieChart.
My code like this:

`new FutureBuilder<List<Map<String, dynamic>>>(
                    future: db.getGroupData(),
                    builder: (BuildContext context, AsyncSnapshot<List<Map<String, dynamic>>> snapshot) {
                      if(snapshot.hasData) {
                        return pieChartCard(context, snapshot.data);
                      } else {
                        return new CircularProgressIndicator();
                      }
                    },
                  ),`
And render function pieChartCard:
`Widget pieChartCard(BuildContext context, List<Map<String, dynamic>> data) {
    Size size = MediaQuery.of(context).size;
    Map<String, double> dataMap = new Map<String, double>();

    data.forEach((item) => dataMap.putIfAbsent(item['tengroup'], () => item['Total'] + 0.0));

    return new Column(
        children: <Widget>[
          new FlatButton(
            onPressed: () => null,
            child: new Text(
              dataMap.length.toString(),
              style: new TextStyle(
                color: Colors.white,
                fontWeight: FontWeight.w900,
                fontSize: 25.0
              ),
            ),
          ),
          new PieChart(
            dataMap: dataMap,
            legendFontColor: Colors.white,
            legendFontSize: 14.0,
            legendFontWeight: FontWeight.w500,
            animationDuration: Duration(milliseconds: 800),
            chartLegendSpacing: 32.0,
            chartRadius: MediaQuery
                .of(context)
                .size
                .width / 2.7,
            showChartValuesInPercentage: true,
            showChartValues: true,
            chartValuesColor: Colors.blueGrey[900].withOpacity(0.9),
          )
        ],
      );
  }`
When i insert a data from other Screen and then back to previous screen but pie chart was not changed. I also logged some script in render function and saw the data was changed.
My chart only change when i exit app and then open it again.
Please let me know how to fix it.
Thanks.

**Comment by apgapg** [comment]
Thanks for reporting. I think i forgot to implement didUpdateWidget function in the state. Thats why its behaving like this. Will update soon

**Comment by apgapg** [comment]
Fixed. Reopen the issue if you find some error. Thanks

**Comment by DjivaCanessane** [comment]
is there any way to animate when data is updated ?

**Comment by apgapg** [comment]
Sorry its not currently supported.
