### ISSUE TITLE
Default color for empty pie chart

### ISSUE THREAD

**Issue by DennisRein** [apgapg/pie_chart#35]
Would it be possible to add a feature, when passing a map with only 0 values to display as a full chart but with an default color, e.g. light grey? 

Other question, when can we expect the update with the number in the middle to be officially released? I am only waiting for that feature.

**Comment by apgapg** [comment]
I think we can have a background color to pie chart cirlcle. This will automatically show the color when empty

**Comment by apgapg** [comment]
For your second question, for which feature you are waiting? You can directly use git repo url instead of version in pubspec.yaml
