### ISSUE TITLE
showChartValueLabel false doesnt work

### ISSUE THREAD

**Issue by chitgoks** [apgapg/pie_chart#41]
it stills hows text inside

current workaround is

```
chartValueStyle: defaultChartValueStyle.copyWith(
    color: Colors.transparent,
),
```

**Comment by apgapg** [comment]
@chitgoks  This param is now renamed as `showChartValueBackground` in `chartValuesOptions`.
This is fixed. Check it LIVE on https://apgapg.github.io/pie_chart/
