### ISSUE TITLE
initial angle is incorrect

### ISSUE THREAD

**Issue by chitgoks** [apgapg/pie_chart#42]
please see attached[
![pie](https://user-images.githubusercontent.com/3955470/85189021-ad1b8580-b2dd-11ea-81b0-b1c793b85058.png)
](url)

when initian angle is zero, the first entry is blue. shouldnt it be in the position of red? if not, then what is the correct angle value for this? i tried -90 but it's not straight, somehow it's around -45 degrees and diagonal

**Comment by chitgoks** [comment]
maybe my understanding is incorrect? setting initialAngle of 55 does the trick. but i dont understand why. thoughts?

**Comment by apgapg** [comment]
Actually the `initialAngle` should be in radians not degrees.
Will try to fix the naming in next commit

**Comment by apgapg** [comment]
@chitgoks I have now added `initialAngleInDegree` in which you can provide angle directly in degress

For eg `initialAngleInDegree: -90`
