### ISSUE TITLE
showChartValues is not working

### ISSUE THREAD

**Issue by cagdas001** [apgapg/pie_chart#48]
Setting `showChartValues` to `false` has no effect, it still displays the chart values.

![chart_issue](https://user-images.githubusercontent.com/28513447/90690033-ac6d8400-e279-11ea-8c69-4dec62f55311.png)

**Steps to Reproduce**

1. Just take an example code block from the documentation, and set `showChartValues` to `false`.
2. Then run and observe

**Expected Result**

Chart values should not be displayed if `showChartValues` is set to `false`

**Actual Result**

Chart values are still being displayed even if `showChartValues` set to `false` This option has no effect at all

**Comment by apgapg** [comment]
This has been fixed on master branch. You can check it LIVE for confirmation https://apgapg.github.io/pie_chart/
