### ISSUE TITLE
Pie Chart Colors

### ISSUE THREAD

**Issue by SJente** [apgapg/pie_chart#5]
Goodmorning Apgapg,

I was wondering if you had any progress on this issue?
#4 

Could really use it in the next couple of days, otherwise i have to use an different plugin..

Have a nice day,
Greetings,
SJente

**Comment by apgapg** [comment]
I am sorry for late response. Allow me 1 or 2 days to publish the new changes. Thanks

**Comment by SJente** [comment]
Great, looking forward to it!

**Comment by apgapg** [comment]
Fixed. Added colorList optional parameter. Reopen the issue if you find some error. Thanks
