### ISSUE TITLE
pub get failed (1; Because flutter_app depends on pie_chart ^4.0.1 which doesn't match any versions, version solving failed.)

### ISSUE THREAD

**Issue by jinfagang** [apgapg/pie_chart#56]
pub get failed (1; Because flutter_app depends on pie_chart ^4.0.1 which doesn't match
any versions, version solving failed.)

**Comment by apgapg** [comment]
Its weird. 
```
dependencies:
  pie_chart: ^4.0.1
```

Are you sure you adding this way?

**Comment by apgapg** [comment]
v5.0.1 released
