### ISSUE TITLE
Use integer or string value for data labels

### ISSUE THREAD

**Issue by vijaytabhatt** [apgapg/pie_chart#60]
Hello  All ,

In My piechart the chart data labels are currently being showned as "3.0" , i need them to be showed as "3" only 
i tried changing the data type of DataMap from <String,double> to <String,int> but it seems the constructor
PieChart(dataMap: dataMap)  only accepts <String,double>

am i missing anything?

**Comment by apgapg** [comment]
You can control decimal places that you can show. See decimal places parameter and set to 0
