### ISSUE TITLE
Migrate pie_chart to null safety

### ISSUE THREAD

**Issue by peterwvj** [apgapg/pie_chart#65]
This package should be migrated to null safety so that other apps and packages depending on it can (more easily) migrate to null safety as well.

Do you have any plans for this?

Thanks.

Related links:

https://dart.dev/null-safety/migration-guide

https://www.youtube.com/watch?v=bvq7wbn4VAA&ab_channel=Flutter

**Comment by apgapg** [comment]
Yes I am planning to do this tomorrow itself.

**Comment by apgapg** [comment]
Done v5.0.0
pie_chart is now fully null safe :blush:

**Comment by peterwvj** [comment]
That was fast :) Thanks a lot!
