### ISSUE TITLE
TextStyle option for center text

### ISSUE THREAD

**Issue by saeedjassani** [apgapg/pie_chart#67]
Hi,

Thanks for this wonderful package.

Is it possibe to let us customize the centerText by providing textStyle option?

Otherwise, it's a very good and customizable package!

**Comment by apgapg** [comment]
Yes we can, it will simple to do.

**Comment by saeedjassani** [comment]
I was just wondering, won't it be better to let user's pass their widget instead of accepting a string and separate TextStyle parameter?

For my use-case, I want to use RichText widget with two different styled texts in centerText.

**Comment by apgapg** [comment]
The way the center text is rendered isn't via widget but via direct methods on canvas. Hence if we provide custom center widget we then need to use Stack and subsequently adjust position to match center

**Comment by saeedjassani** [comment]
Could you please point me to the code where it is rendered?
