### ISSUE TITLE
Request: Omit zero values from chart

### ISSUE THREAD

**Issue by guyzk** [apgapg/pie_chart#7]
First of all great lib! good work!
I would like to request an option to omit zero values from the chart (not from the legend) as right now if some of the values are o it shows 0% between the other groups and it looks weird...

**Comment by apgapg** [comment]
That's indeed a bug. It shouldnt show 0 on chart but should show only in legends. Will definitely fix it by today itself.

**Comment by apgapg** [comment]
Done check v1.0.0
