### ISSUE TITLE
Gradient Color Mix In Ring Shape.

### ISSUE THREAD

**Issue by wajahat414** [apgapg/pie_chart#85]
![WhatsApp Image 2022-05-23 at 11 14 10 AM](https://user-images.githubusercontent.com/73127111/169767249-d4ee70c5-24f6-4411-a404-2db6feaf3f68.jpeg)
![WhatsApp Image 2022-05-23 at 11 34 29 AM](https://user-images.githubusercontent.com/73127111/169767439-ed9b27a3-81e6-4695-8170-8c9ac3cc55a4.jpeg)

Specially This blueCorner Gradient

**Comment by apgapg** [comment]
Closing this in favor of #83
